// Code generated by protoc-gen-go.
// source: loginserv.proto
// DO NOT EDIT!

/*
Package loginserv_msg is a generated protocol buffer package.

syntax="proto3";

It is generated from these files:
	loginserv.proto

It has these top-level messages:
	LoginMsg
	LoginMsgRes
	PayGetIdMsg
	PayGetIdMsgRes
	PaySuccMsg
	PaySuccMsgRes
*/
package loginserv_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMD int32

const (
	CMD_LOGIN_MSG      CMD = 327681
	CMD_PAY_GET_ID_MSG CMD = 327682
	CMD_PAY_SUCC_MSG   CMD = 327683
)

var CMD_name = map[int32]string{
	327681: "LOGIN_MSG",
	327682: "PAY_GET_ID_MSG",
	327683: "PAY_SUCC_MSG",
}
var CMD_value = map[string]int32{
	"LOGIN_MSG":      327681,
	"PAY_GET_ID_MSG": 327682,
	"PAY_SUCC_MSG":   327683,
}

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}
func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}
func (x *CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_value, data, "CMD")
	if err != nil {
		return err
	}
	*x = CMD(value)
	return nil
}
func (CMD) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LoginMsg struct {
	Ip               *string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port             *uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	GatewayCnt       *uint32 `protobuf:"varint,3,opt,name=gateway_cnt" json:"gateway_cnt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginMsg) Reset()                    { *m = LoginMsg{} }
func (m *LoginMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginMsg) ProtoMessage()               {}
func (*LoginMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginMsg) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *LoginMsg) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *LoginMsg) GetGatewayCnt() uint32 {
	if m != nil && m.GatewayCnt != nil {
		return *m.GatewayCnt
	}
	return 0
}

type LoginMsgRes struct {
	Platform         *uint32 `protobuf:"varint,1,opt,name=platform" json:"platform,omitempty"`
	Account          *string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Session          *string `protobuf:"bytes,3,opt,name=session" json:"session,omitempty"`
	WxUnionid        *string `protobuf:"bytes,4,opt,name=wx_unionid" json:"wx_unionid,omitempty"`
	WxNick           *string `protobuf:"bytes,5,opt,name=wx_nick" json:"wx_nick,omitempty"`
	WxHeadurl        *string `protobuf:"bytes,6,opt,name=wx_headurl" json:"wx_headurl,omitempty"`
	WxHead           []byte  `protobuf:"bytes,7,opt,name=wx_head" json:"wx_head,omitempty"`
	WxSex            *uint32 `protobuf:"varint,8,opt,name=wx_sex" json:"wx_sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginMsgRes) Reset()                    { *m = LoginMsgRes{} }
func (m *LoginMsgRes) String() string            { return proto.CompactTextString(m) }
func (*LoginMsgRes) ProtoMessage()               {}
func (*LoginMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginMsgRes) GetPlatform() uint32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *LoginMsgRes) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginMsgRes) GetSession() string {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return ""
}

func (m *LoginMsgRes) GetWxUnionid() string {
	if m != nil && m.WxUnionid != nil {
		return *m.WxUnionid
	}
	return ""
}

func (m *LoginMsgRes) GetWxNick() string {
	if m != nil && m.WxNick != nil {
		return *m.WxNick
	}
	return ""
}

func (m *LoginMsgRes) GetWxHeadurl() string {
	if m != nil && m.WxHeadurl != nil {
		return *m.WxHeadurl
	}
	return ""
}

func (m *LoginMsgRes) GetWxHead() []byte {
	if m != nil {
		return m.WxHead
	}
	return nil
}

func (m *LoginMsgRes) GetWxSex() uint32 {
	if m != nil && m.WxSex != nil {
		return *m.WxSex
	}
	return 0
}

type PayGetIdMsg struct {
	Platform         *uint32 `protobuf:"varint,1,opt,name=platform" json:"platform,omitempty"`
	Account          *string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Product          *string `protobuf:"bytes,3,opt,name=product" json:"product,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PayGetIdMsg) Reset()                    { *m = PayGetIdMsg{} }
func (m *PayGetIdMsg) String() string            { return proto.CompactTextString(m) }
func (*PayGetIdMsg) ProtoMessage()               {}
func (*PayGetIdMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PayGetIdMsg) GetPlatform() uint32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *PayGetIdMsg) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *PayGetIdMsg) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

type PayGetIdMsgRes struct {
	PayId            *string `protobuf:"bytes,1,opt,name=pay_id" json:"pay_id,omitempty"`
	UrlCallback      *string `protobuf:"bytes,2,opt,name=url_callback" json:"url_callback,omitempty"`
	Product          *string `protobuf:"bytes,3,opt,name=product" json:"product,omitempty"`
	ZfbUrlCallback   *string `protobuf:"bytes,4,opt,name=zfb_url_callback" json:"zfb_url_callback,omitempty"`
	WxUrlCallback    *string `protobuf:"bytes,5,opt,name=wx_url_callback" json:"wx_url_callback,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PayGetIdMsgRes) Reset()                    { *m = PayGetIdMsgRes{} }
func (m *PayGetIdMsgRes) String() string            { return proto.CompactTextString(m) }
func (*PayGetIdMsgRes) ProtoMessage()               {}
func (*PayGetIdMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PayGetIdMsgRes) GetPayId() string {
	if m != nil && m.PayId != nil {
		return *m.PayId
	}
	return ""
}

func (m *PayGetIdMsgRes) GetUrlCallback() string {
	if m != nil && m.UrlCallback != nil {
		return *m.UrlCallback
	}
	return ""
}

func (m *PayGetIdMsgRes) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

func (m *PayGetIdMsgRes) GetZfbUrlCallback() string {
	if m != nil && m.ZfbUrlCallback != nil {
		return *m.ZfbUrlCallback
	}
	return ""
}

func (m *PayGetIdMsgRes) GetWxUrlCallback() string {
	if m != nil && m.WxUrlCallback != nil {
		return *m.WxUrlCallback
	}
	return ""
}

type PaySuccMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PaySuccMsg) Reset()                    { *m = PaySuccMsg{} }
func (m *PaySuccMsg) String() string            { return proto.CompactTextString(m) }
func (*PaySuccMsg) ProtoMessage()               {}
func (*PaySuccMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PaySuccMsgRes struct {
	Product          *string `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
	Amount           *string `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PaySuccMsgRes) Reset()                    { *m = PaySuccMsgRes{} }
func (m *PaySuccMsgRes) String() string            { return proto.CompactTextString(m) }
func (*PaySuccMsgRes) ProtoMessage()               {}
func (*PaySuccMsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PaySuccMsgRes) GetProduct() string {
	if m != nil && m.Product != nil {
		return *m.Product
	}
	return ""
}

func (m *PaySuccMsgRes) GetAmount() string {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginMsg)(nil), "loginserv_msg.login_msg")
	proto.RegisterType((*LoginMsgRes)(nil), "loginserv_msg.login_msg_res")
	proto.RegisterType((*PayGetIdMsg)(nil), "loginserv_msg.pay_get_id_msg")
	proto.RegisterType((*PayGetIdMsgRes)(nil), "loginserv_msg.pay_get_id_msg_res")
	proto.RegisterType((*PaySuccMsg)(nil), "loginserv_msg.pay_succ_msg")
	proto.RegisterType((*PaySuccMsgRes)(nil), "loginserv_msg.pay_succ_msg_res")
	proto.RegisterEnum("loginserv_msg.CMD", CMD_name, CMD_value)
}

func init() { proto.RegisterFile("loginserv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0x87, 0xd5, 0x3f, 0x6f, 0xdb, 0xdc, 0x9b, 0xa4, 0x91, 0xa9, 0x84, 0x47, 0x94, 0x09, 0x31,
	0xb0, 0xb0, 0x31, 0x81, 0x5a, 0x54, 0x55, 0xa2, 0x80, 0x54, 0x18, 0x98, 0x2c, 0xd7, 0x49, 0x43,
	0x44, 0x1a, 0x47, 0x71, 0x42, 0x0b, 0x03, 0x2a, 0xf0, 0x39, 0xf8, 0xae, 0x9c, 0x1d, 0x51, 0x52,
	0x89, 0x81, 0xf1, 0x9e, 0x5c, 0xee, 0x9e, 0xdf, 0x19, 0xfa, 0x89, 0x8c, 0xe2, 0x54, 0x85, 0xf9,
	0xd3, 0x71, 0x96, 0xcb, 0x42, 0x12, 0x67, 0x0b, 0xd8, 0x52, 0x45, 0xfe, 0x29, 0x58, 0x06, 0xe8,
	0x82, 0x00, 0x34, 0xe3, 0x8c, 0x36, 0x0e, 0x1a, 0x87, 0x16, 0xb1, 0xa1, 0x9d, 0xc9, 0xbc, 0xa0,
	0x4d, 0xac, 0x1c, 0xb2, 0x07, 0xff, 0x23, 0x5e, 0x84, 0x2b, 0xfe, 0xcc, 0x44, 0x5a, 0xd0, 0x96,
	0x86, 0xfe, 0x67, 0x03, 0x9c, 0xed, 0xcf, 0x2c, 0x0f, 0x15, 0xf1, 0xa0, 0x97, 0x25, 0xbc, 0x58,
	0xc8, 0x7c, 0x69, 0xc6, 0x38, 0xa4, 0x0f, 0x5d, 0x2e, 0x84, 0x2c, 0xd3, 0x6a, 0x92, 0xa5, 0x81,
	0x0a, 0x95, 0x8a, 0x65, 0x6a, 0xa6, 0x58, 0x04, 0xb7, 0xae, 0xd6, 0xac, 0x4c, 0x91, 0xc4, 0x01,
	0x6d, 0x7f, 0x37, 0x21, 0x4b, 0x63, 0xf1, 0x48, 0xff, 0xd5, 0x9a, 0x1e, 0x42, 0x1e, 0x94, 0x79,
	0x42, 0x3b, 0xb5, 0x26, 0xcd, 0x68, 0x17, 0x81, 0x4d, 0x5c, 0xe8, 0x20, 0x50, 0xe1, 0x9a, 0xf6,
	0x8c, 0xdf, 0x08, 0xdc, 0x0c, 0x85, 0xa3, 0xb0, 0x60, 0x71, 0x60, 0x02, 0xfe, 0xcd, 0x0f, 0x0f,
	0x15, 0x94, 0xa2, 0x4a, 0x69, 0xf9, 0xaf, 0x40, 0x76, 0xa7, 0x98, 0xa4, 0xb8, 0x4b, 0x53, 0x34,
	0xae, 0xce, 0x35, 0x00, 0x1b, 0xcd, 0x98, 0xe0, 0x49, 0x32, 0xe7, 0xa8, 0xfd, 0xfb, 0x30, 0x42,
	0xc1, 0x7b, 0x59, 0xcc, 0xd9, 0x4e, 0x6b, 0x15, 0x79, 0x1f, 0xfa, 0xfa, 0x0c, 0xf5, 0x0f, 0x26,
	0xba, 0xef, 0x82, 0xad, 0x37, 0xa9, 0x52, 0x08, 0xf3, 0x62, 0x27, 0xe0, 0xd5, 0x6b, 0x63, 0x53,
	0xdb, 0x53, 0xe9, 0xa0, 0x1e, 0x5f, 0xfe, 0xa4, 0x3a, 0x3a, 0x83, 0xd6, 0x70, 0x3a, 0xc2, 0x3e,
	0xeb, 0xf2, 0x7a, 0x3c, 0xb9, 0x62, 0xd3, 0xd9, 0xd8, 0x7b, 0xdb, 0x0c, 0x50, 0xdb, 0xbd, 0x39,
	0xbf, 0x67, 0xe3, 0x8b, 0x5b, 0x36, 0x19, 0x19, 0xfa, 0x8e, 0x94, 0x80, 0xad, 0xe9, 0xec, 0x6e,
	0x38, 0x34, 0xec, 0x63, 0x33, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x7b, 0x11, 0x7b, 0x49,
	0x02, 0x00, 0x00,
}
